#!/bin/bash

echo "input file name"
read name

echo "#!/bin/bash" > ${name}

vi ${name}

echo "your chmod file" 
read input

chmod u+x ${input}

echo "input commit message"
read var

git add .
git commit -m "${var}"
git push
